# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16sz2jXEePPyzugVycRyY8evjYJPoh0i3
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 30 + np.random.randn(10)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 10, where=(ys > 1), facecolor='g', alpha=1)

plt.title("increasing day wise")
plt.show()